" Uncomment this if running Arch
" runtime! archlinux.vim

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1
"
" These two are required for Vundle
set nocompatible
filetype off 
" Vundle stuff below
" set rtp+=/usr/share/vim/vimfiles/autoload/vundle.vim
call vundle#begin()
" Plugins go below
Plugin 'VundleVim/Vundle.vim'       " let Vundle manage Vundle, required
Plugin 'vim-syntastic/syntastic'    " Syntastic
Plugin 'jiangmiao/auto-pairs'       " Auto pair creation
Plugin 'scrooloose/nerdtree'        " File viewer
Plugin 'xolox/vim-misc'             " For vim-easytags
Plugin 'xolox/vim-easytags'         " Streamlines tagging operations
Plugin 'fidian/hexmode'             " Adds a hex editor

call vundle#end()
" Remember to :VundleInstall 

" Quality of Life
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set selectmode=mouse
set mouse=a
set nobackup
set nowritebackup
set history=50
set ruler
set number
set encoding=utf-8

" Hex editor mode
map <C-h> :Hexmode<CR> " ctrl + h
let g:hexmode_patterns = '*.bin,*.exe,*.dat,*.o'
let g:hexmode_autodetect = 1

" Nerd Tree
map <C-n> :NERDTreeToggle<CR>

" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Disable beeping
set noerrorbells visualbell t_vb=
if has('autocmd')
  autocmd GUIEnter * set visualbell t_vb=
endif
